### PR TITLE
Grunt fh build

### PR DESCRIPTION
**Pull request by lgriffin**

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:
- The code changes conform to the contributing & code style guides for this component (if they exist)
- A component owner should review your change (we've tagged these above)
- Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
- There should be an associated fhcap PR with this change - please provide a link to this
- If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
- Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
- Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

In order to update fhcap with your component change please execute:
`fhcap component update fh-logger 0.4.1 19`

**Comment by danbev** [comment]
@lgriffin The commit history in this look a little odd. Is there anything apart from 534f3598cc96c9cf2ba6e229cfcc657a5825e2dc that is required here? If not I can just cherry-pick that and merge it.

**Comment by lgriffin** [comment]
Yeah @danbev sorry it was on an old branch and somehow the history got sucked into it the only valid change is the version bump!

**Comment by lgriffin** [comment]
feel free to close this PR and issue one yourself against it if it is cleaner / easier to do!

**Comment by danbev** [comment]
@lgriffin No problems at all! 

Merged as 01b1d50.

**Pull request closed without merging**
