### PR TITLE
Updating grunt-fh-build and adding ESlint

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Update grunt-fh-build to the latest version and replace jslint with
ESlint.

Modifications:
Used npm to update grunt-fh-build and to install ESlint.
Updated lib/fh_logger.js to fix the warnings reported by ESlint

Result:
Default grunt task passes without any ESlint warnings:
$ grunt

JIRA:
https://issues.jboss.org/browse/RHMAP-5748

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:
- The code changes conform to the contributing & code style guides for this component (if they exist)
- A component owner should review your change (we've tagged these above)
- Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
- There should be an associated fhcap PR with this change - please provide a link to this
- If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
- Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
- Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

In order to update fhcap with your component change please execute:
`fhcap component update fh-logger 0.4.1 20`

**Comment by grdryn** [comment]
@danbev Just took a quick look at this...is there anything blocking us from specifying the latest (1.0.1) version of grunt (and updating other dev dependencies also)?

**Comment by danbev** [comment]
@grdryn There seems to be a few plugins that require grunt@0.4.5. Let me try and see if I can upgrade them (will be later today before I get to it)

**Comment by grdryn** [comment]
@danbev also, I think it could be good to add "test" and "version" scripts to package.json. Take a look at fh-aaa-client for an example (can copy `scripts` section of package.json directly from there to here I think). Let me know if you want more info on that :)

**Comment by danbev** [comment]
@grdryn Ah I missed them completely. Let me take another look.

**Comment by danbev** [comment]
@grdryn So the test script is run when I do `npm test`. But I'm not aware of when the version script would be run. It says [here](https://docs.npmjs.com/misc/scripts#description) that it is run before a version bump. I've only updated the version of package.json manually. Should I have been (or should I start) using `npm-version` now?

**Comment by grdryn** [comment]
@danbev I've mainly been bumping manually also (which I think we'll even still have to do for the components that have a `-BUILD-NUMBER` extension, because they're not semver compliant). For other things, I think using the `npm version` command will be good when we're releasing a version, because it will:
- bump the version in package.json and npm-shrinkwrap.json
- run whatever we've got in version script
- Commit the changes
- Tag the release

So I guess it's a little similar to the maven release plugin.

We probably won't start using it straight away, but having this script in the package.json will get us closer to the point where we can automate releasing/publishing from the build server (and then do the next step, like update the version of this in things that depend on it, and PR against those, and filter all the way up to fhcap).

**Comment by danbev** [comment]
@grdryn Thanks for the details Ger, much appreciated!

**Comment by danbev** [comment]
@grdryn I've updated the PR, adding the missing scripts and also updated the dev dependencies and the version of Bunyan to the latest. This all passed locally but I just noticed that the build server failed. I'll look into the reason for this. 
It was me forgetting to run npm shrinkwrap for the 100th time :disappointed: I've now removed the updating of Buynan as it is not a dev dependency and should be done as a separate PR followed by a publishing of a new version.

**Comment by grdryn** [comment]
@danbev it's great that at least the invalid shrinkwrap files are being caught now by a simple `npm ls` in the build job! :)

Before we merge this, do you know what has changed in the fh-logger.js file? There's a change or two in a switch block (that has a nested switch also), but the git diff is output here in a way that makes it quite difficult to tell what exactly has changed. I've got a feeling that it's a new `break` or something, but I'm not able to tell! :)

**Comment by danbev** [comment]
@grdryn The changes in that particular section are indentations of the case clauses. They were indented more that they should have been according to the rules.

**Comment by grdryn** [comment]
@danbev Cool, looks good to me in that case :+1:

**Pull request merged**
